export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_FLAG_CHANGE = 'USER_FLAG_CHANGE';

export const USER_VIDEO_UPLOAD_REQUEST = 'USER_VIDEO_UPLOAD_REQUEST';
export const USER_VIDEO_UPLOAD_SUCCESS = 'USER_VIDEO_UPLOAD_SUCCESS';
export const USER_VIDEO_UPLOAD_FAIL = 'USER_VIDEO_UPLOAD_FAIL';

export const USER_VIDEOS_REQUEST = 'USER_VIDEOS_REQUEST';
export const USER_VIDEOS_SUCCESS = 'USER_VIDEOS_SUCCESS';
export const USER_VIDEOS_FAIL = 'USER_VIDEOS_FAIL';

export const USER_UPLOAD_REQUEST = 'USER_UPLOAD_REQUEST';
export const USER_UPLOAD_SUCCESS = 'USER_UPLOAD_SUCCESS';
export const USER_UPLOAD_FAIL = 'USER_UPLOAD_FAIL';