export const VIDEO_LIST_REQUEST = 'VIDEO_LIST_REQUEST';
export const VIDEO_LIST_SUCCESS = 'VIDEO_LIST_SUCCESS';
export const VIDEO_LIST_FAIL = 'VIDEO_LIST_FAIL';

export const VIDEO_DETAILS_REQUEST = 'VIDEO_DETAILS_REQUEST';
export const VIDEO_DETAILS_SUCCESS = 'VIDEO_DETAILS_SUCCESS';
export const VIDEO_DETAILS_FAIL = 'VIDEO_DETAILS_FAIL';

export const VIDEO_DELETE_REQUEST = 'VIDEO_DELETE_REQUEST';
export const VIDEO_DELETE_SUCCESS = 'VIDEO_DELETE_SUCCESS';
export const VIDEO_DELETE_FAIL = 'VIDEO_DELETE_FAIL';

export const LIKE_VIDEO_REQUEST = 'LIKE_VIDEO_REQUEST';
export const LIKE_VIDEO_SUCCESS = 'LIKE_VIDEO_SUCCESS';
export const LIKE_VIDEO_FAIL = 'LIKE_VIDEO_FAIL';

export const COMMENT_VIDEO_REQUEST = 'LIKE_VIDEO_REQUEST';
export const COMMENT_VIDEO_SUCCESS = 'LIKE_VIDEO_SUCCESS';
export const COMMENT_VIDEO_FAIL = 'LIKE_VIDEO_FAIL';

export const VIEWS_VIDEO_REQUEST = 'VIEWS_VIDEO_REQUEST';
export const VIEWS_VIDEO_SUCCESS = 'VIEWS_VIDEO_SUCCESS';
export const VIEWS_VIDEO_FAIL = 'VIEWS_VIDEO_FAIL';